export const SET_CURRENT_ACTIVE_NOTE = 'SET_CURRENT_ACTIVE_NOTE';
export const NEW_NOTE = 'NEW_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const TOGGLE_LIST_SHOW = 'TOGGLE_LIST_SHOW';
